name: Build
on:
  workflow_dispatch:
    input:
  push:
    branches:
      - main
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Build APK
        run: ./.github/workflows/scripts/setup-react-native-app.sh
      - name: Push APK update
        run: |
          git config --global user.email "bam.flashlight@gmail.com"
          git config --global user.name "flashlight-bot"
          git add apks
          git push
